spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_client_db?currentSchema=ms_client_schema
    username: postgres
    password: z3V52gBu7vDC626
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080
